# Jekyll configuration

name: Menion online
description: Software Developer & LoMan in one person.

# Url is currently only used only for the RSS feed in feed.xml
url: https://menion.asamm.com
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
#baseurl: '/jekyll-clean-dark'
baseurl: ''

author: Jiří M. aka Menion
copyright: 2019-2019

share:
  facebook: false
  twitter: false
  linkedin: false
  pinterest: false
  email: false

social:
  github: menion
  stackoverflow: ''
  linkedin:
  instagram: ''
  lastfm: ''
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-45096695-12

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: menion
comments: true

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
